sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - glpk
      
before_script:
- wget http://packages.seqan.de/razers3/razers3-3.4.0-Linux-x86_64.tar.bz2
- tar xf razers3-3.4.0-Linux-x86_64.tar.bz2
script:
  nosetests 
